name: prism_sync
description: Dart bindings for prism-sync encrypted CRDT sync library
version: 0.1.1

environment:
  sdk: ^3.11.1

dependencies:
  code_assets: ^1.2.1
  flutter_rust_bridge: 2.12.0
  hooks: ^2.0.2
  meta: ^1.11.0
  native_toolchain_rust: ^1.0.4+0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
