/// Cross-language test vectors for verifying Rust ↔ Dart byte-level compatibility.
///
/// These expected values were generated by running:
///   dart run test/generate_cross_language_vectors.dart
/// in the Prism Flutter project against libsodium + PointyCastle.
///
/// If ANY of these tests fail, the Rust implementation is NOT wire-compatible
/// with the Dart implementation and deploying would corrupt existing user data.

#[test]
fn argon2id_matches_dart() {
    // Dart: sodium.crypto.pwhash(password: utf8("test_password") || [0x01]*16,
    //       salt: [0x02]*16, opsLimit: 3, memLimit: 67108864, alg: argon2id13)
    let password = b"test_password";
    let secret_key = [0x01u8; 16];
    let salt = [0x02u8; 16];
    let mek = prism_sync_crypto::kdf::derive_mek(password, &secret_key, &salt).unwrap();
    assert_eq!(
        prism_sync_crypto::hex::encode(&mek),
        "3dea0d7d0b5e9cc09259cfac83c76f525bab383e409e3518c460afbea04c1c66"
    );
}

#[test]
fn hkdf_epoch_zero_matches_dart() {
    // Dart: HKDFKeyDerivator(SHA256Digest()) with
    //       ikm=[0x2a]*32, salt=be_u32(0) (4 zero bytes), info="epoch_sync\0"
    let dek = [0x2au8; 32];
    let key = prism_sync_crypto::kdf::derive_epoch_zero_key(&dek).unwrap();
    assert_eq!(
        prism_sync_crypto::hex::encode(&key),
        "1c4d5646fec1fc9eedfeea0c69c9e73f3bff899d89a0b27271db439c8e621217"
    );
}

#[test]
fn hkdf_database_key_matches_dart() {
    // Dart: HKDFKeyDerivator(SHA256Digest()) with
    //       ikm=[0x2a]*32, salt=null (→ HashLen zeros), info="prism_database_key"
    // Rust must use Hkdf::new(None, ikm) for empty salt to match.
    let dek = [0x2au8; 32];
    let key = prism_sync_crypto::kdf::derive_database_key(&dek).unwrap();
    assert_eq!(
        prism_sync_crypto::hex::encode(&key),
        "e63820d6c665f5eff3057f956e113503e18066f0fbcfd922cf99f9ab9908a885"
    );
}

#[test]
fn hkdf_group_invite_matches_dart() {
    // Dart: HKDFKeyDerivator(SHA256Digest()) with
    //       ikm=[0x2a]*32, salt=null (→ HashLen zeros), info="prism_group_invite"
    let dek = [0x2au8; 32];
    let key = prism_sync_crypto::kdf::derive_group_invite_secret(&dek).unwrap();
    assert_eq!(
        prism_sync_crypto::hex::encode(&key),
        "8d833f5fb31f9121a8c649472824eafd892062b798b402c13d25a351a204e267"
    );
}

#[test]
fn bip39_entropy_to_mnemonic_matches_dart() {
    // Dart: bip39.entropyToMnemonic("000102030405060708090a0b0c0d0e0f")
    let entropy = prism_sync_crypto::hex::decode("000102030405060708090a0b0c0d0e0f").unwrap();
    let mnemonic = prism_sync_crypto::mnemonic::from_bytes(&entropy).unwrap();
    assert_eq!(
        mnemonic,
        "abandon amount liar amount expire adjust cage candy arch gather drum buyer"
    );
}

#[test]
fn secretbox_matches_dart() {
    // Dart: sodium.crypto.secretBox.easy(message: [0x42]*32,
    //       nonce: [0x03]*24, key: <known key>)
    // This verifies XSalsa20-Poly1305 wire format compatibility.
    let key = prism_sync_crypto::hex::decode(
        "db84a725d43098af93af9ed0caab6816d78e717dcd0081b1f124017fa942ba1c",
    )
    .unwrap();
    let nonce = [0x03u8; 24];
    let plaintext = [0x42u8; 32];
    let expected_ciphertext = prism_sync_crypto::hex::decode(
        "53364972b9eff1856cb2aa5459cc9666e8cc05a9bae7f2801434e9db9d9c76a7e00e8bc926bd1d02fba122016349627e"
    ).unwrap();

    // Encrypt with known nonce (test-only helper)
    let blob =
        prism_sync_crypto::aead::secretbox_wrap_with_nonce(&key, &plaintext, &nonce).unwrap();

    // blob = nonce || ciphertext+MAC, so strip the nonce to compare just the ciphertext
    let ciphertext = &blob[24..];
    assert_eq!(
        prism_sync_crypto::hex::encode(ciphertext),
        prism_sync_crypto::hex::encode(&expected_ciphertext),
        "XSalsa20-Poly1305 ciphertext must match Dart libsodium output"
    );

    // Also verify decryption works
    let decrypted = prism_sync_crypto::aead::secretbox_unwrap(&key, &blob).unwrap();
    assert_eq!(decrypted, plaintext);
}

#[test]
fn hkdf_empty_salt_equals_hashlen_zero_salt() {
    // Proves that our None-for-empty-salt fix is correct:
    // HKDF with empty salt must produce the same output as HKDF with
    // an explicit 32-byte zero salt (SHA-256 HashLen = 32).
    let ikm = [0x2au8; 32];
    let info = b"test_info";

    let key_empty_salt = prism_sync_crypto::kdf::derive_subkey(&ikm, &[], info).unwrap();
    let key_zero_salt = prism_sync_crypto::kdf::derive_subkey(&ikm, &[0u8; 32], info).unwrap();

    assert_eq!(
        *key_empty_salt, *key_zero_salt,
        "empty salt and 32-zero-byte salt must produce identical HKDF output"
    );
}
